spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hsabau?serverTimezone=UTC&nullDatabaseMeansCurrent=true"  # TODO!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "passwort"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        use_sql_comments: true
        ddl-auto: update
    generate-ddl: true

logging:
  level:
    root: debug

camunda:
  bpm:
    database:
      schema-update: true
      type: mysql
    admin-user:
      id: demo
      password: demo

server:
  port: 8088
